### ISSUE TITLE
Support regenerate weekly report only

### ISSUE THREAD

**Issue by breezewish** [siddontang/work-reporter#2]
Sprint is a very special and restricted object in JIRA: itself cannot be deleted and once it is closed it cannot be removed from tasks as well.

We need a standalone function to re-generate weekly report for specific sprint without changing sprints, so that the (permanent) affection to tasks can be minimized.

**Comment by siddontang** [comment]
so the command may be:

```
work-reporter weekly create-new-sprint
work-reporter weekly generate-reporter
work-reporter weekly close-current-sprint
```

Feel free to send a PR
